create table category (
    id int generated by default as identity primary key,
    name varchar(50) not null,
    description varchar(100)
);

create table product (
    id int generated by default as identity primary key,
    name varchar(50) not null,
    description varchar(200),
    price numeric(15,2) not null check (price > 0),
    category_id int references category(id) on delete set null,
    added_at timestamp not null,
    is_active boolean not null
);

create table image (
    id int generated by default as identity primary key,
    data bytea not null,
    content_type varchar(50) not null,
    size int not null check (size > 0),
    product_id int not null unique references product(id) on delete cascade
);
